### ISSUE TITLE
Configuration for rule "spaced-comment" is invalid

### ISSUE THREAD

**Issue by Nileshbirari** [strongloop/eslint-config-loopback#27]
# Description/Steps to reproduce
run npm run lint
package.json looks like 
"scripts": {
    "start": "cross-env NODE_ENV=dev node server/server.js",
    "pretest": "eslint .",
    "posttest": "nsp check",
    "lint": "eslint ."
}
.eslintrc 
{
  "extends": "loopback",
  "rules": {
    "spaced-comment": "off"
  }
}
Get error 
eslint .

loopback:
        Configuration for rule "spaced-comment" is invalid:
        Value "data["1"].block.balanced" has additional properties.

Referenced from: C:\Users\IBM_ADMIN\Documents\Trainings\nodejs\trackerstat_porting\trackerng\.eslintrc
Error: loopback:
        Configuration for rule "spaced-comment" is invalid:
        Value "data["1"].block.balanced" has additional properties.

# Link to reproduction sandbox

# Expected result

# Additional information

**Comment by harryadel** [comment]
I had the same problem, all you have to do is reinstall `eslint` to the latest version, anything 4.x.x will suffice. And don't forget to remove `"spaced-comment": "off"` since this may cause additional errors.

**Comment by dhmlau** [comment]
@Nileshbirari , seems like this issue has been resolved.  Is it good to close?  Thanks.

**Comment by dhmlau** [comment]
@Nileshbirari , I'm closing this ticket as resolved.  If you still encounter this issue, please feel free to reopen this ticket.  Thanks.
