### ISSUE TITLE
Add lint rule for function params

### ISSUE THREAD

**Issue by Danwakeem** [strongloop/eslint-config-loopback#28]
# Description/Steps to reproduce
When opening the strongloop/loopback-swagger#127 it was brought up that adding a lint rule to enforce argument formatting might be beneficial. 

# Link to reproduction sandbox
- Example of rule added to [loopback swagger `.eslintrc`](https://github.com/Danwakeem/loopback-swagger/tree/linter)

# Expected result
Function arguments should follow a consistent patter like the one below.
```
var doc = createAPIDoc({
      returns: [
        {
          arg: 'data',
          type: ['customType'],
        },
      ],
    },
    null,
    typeRegistry);
```

## Actual result
Currently something like this could pass a lint test.
```
var doc = createAPIDoc({
      returns: [
        {
          arg: 'data',
          type: ['customType'],
        },
      ],
    }, null, typeRegistry);
```

# Additional information
You can see an example of the lint rule not catching an error in the ticket I posted in the description strongloop/loopback-swagger#127

**Comment by dhmlau** [comment]
Closing as PR #29 has landed.  Thanks for your contribution!
