### ISSUE TITLE
"eslint-plugin-mocha@4.12.1" throws a warning when running `npm install` with ESLint@5.8.0 installed

### ISSUE THREAD

**Issue by felladrin** [strongloop/eslint-config-loopback#32]
# Description/Steps to reproduce

`npm install` throws the warning: `eslint-plugin-mocha@4.12.1 requires a peer of eslint@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.`

Currently eslint version installed:
`"eslint": "^5.8.0",`

I believe that updating [eslint-plugin-mocha](https://www.npmjs.com/package/eslint-plugin-mocha) to its latest version (5.2.0) can solve the problem.

# Expected result

No warnings when running `npm install`. 

# Additional information

```
$ node -e 'console.log(process.platform, process.arch, process.versions.node)'
linux x64 10.13.0

$ npm ls --prod --depth 0 | grep loopback
├── loopback@3.23.2
├── loopback-boot@2.27.1
├── loopback-component-explorer@6.3.1
├── loopback-connector-postgresql@3.4.0
├── loopback-counts-mixin@1.0.1
├── loopback-ds-computed-mixin@2.0.4
├── loopback-ds-timestamp-mixin@3.4.1
```

**Comment by dhmlau** [comment]
@felladrin , would you like to submit a patch?
